# Generated by Django 3.2.3 on 2021-05-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210522_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Write Something About Yourself!'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default="What's your gender?", max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Where are you from?', max_length=100),
        ),
    ]
